silverstripe/silverstripe-mfa

_config/config.yml, src/AuthenticationMethod/AuthenticatorInterface.php, src/AuthenticationMethodInterface.php, src/BasicMath/Method.php, src/BasicMath/MethodAuthenticator.php, src/Extensions/MemberExtension.php, src/LoginHandler.php, src/MemberAuthenticator.php, src/Model/AuthenticationMethod.php, src/SessionStore.php
- Adds a MemberAuthenticator that overrides the LoginHandler
- Extends the base MemberAuthenticator LoginHandler to insert another step into the login process
- Creates a model for registering MFA methods - hasMany on a Member
- Stores the type of MFA method
- Holds additional arbitrary data as a blob for that specific registration of the MFA method
- Creates a MemberExtension for storing some detail on Member
- Adds a "BasicMath" MFA method for testing and POC
I've taken the liberty of deciding to create a `SessionStore` class that is used for containing state an MFA method stores in the session. I've done this for a few reasons:
- Keeps state added to the session by plug-in modules contained. Prevents bleeding state between authenticators
- Allows the base MFA module to reliably clear …
=> First cut at creating models and login interfaces for MFA

_config/config.yml, src/Authenticator/LoginHandler.php, src/Extension/MemberExtension.php, src/Method/MethodInterface.php, src/Model/RegisteredMethod.php, src/Service/MethodRegistry.php, src/Store/SessionStore.php, tests/php/Authenticator/LoginHandlerTest.php, tests/php/Authenticator/LoginHandlerTest.yml, tests/php/Service/MethodRegistryTest.php, tests/php/Stub/BasicMath/Method.php
- The current Members registered MFA methods are provided
- Additional methods that haven't been registered by the user also show up
- The default method will be provided if set
- Fixed an issue where routing was not correct as the base `mfa` endpoint would catch all other routes
This also adds the `MethodRegistry` service to manage methods.
Resolves #6
=> NEW The MFA schema endpoint now returns relevant details

src/Authenticator/LoginHandler.php, src/Model/RegisteredMethod.php, src/Service/MethodRegistry.php, src/Store/SessionStore.php, src/Store/StoreInterface.php, tests/php/Authenticator/RegisterHandlerTest.php, tests/php/Authenticator/RegisterHandlerTest.yml, tests/php/Stub/BasicMath/MethodRegisterHandler.php
This PR fleshes out the `mfa/register` endpoint, covering both GET (startRegistration) and POST (finishRegistration) methods.
It also includes some tweaks to SessionStore, making its behaviour more sensible.
=> Implement MFA registration API endpoints

src/Authenticator/LoginHandler.php, src/Exception/MemberNotFoundException.php, src/Extension/MemberExtension.php, src/Service/EnforcementManager.php, src/Service/MethodRegistry.php, src/Service/SchemaGenerator.php, tests/php/Authenticator/LoginHandlerTest.php, tests/php/Service/EnforcementManagerTest.php, tests/php/Service/EnforcementManagerTest.yml, tests/php/Service/SchemaGeneratorTest.php, tests/php/Service/SchemaGeneratorTest.yml
* Refactors a little of LoginHandler to move into a SchemaGenerator service
* Adds logic for determining whether the user can skip MFA and whether to redirect to MFA into the schema
* Adds an endpoint to handle processing of the "skip MFA" logic
Resolves #14
=> Backend implementation for ability to skip MFA registration/login process

_config/state.yml, src/BackupCode/Method.php, src/Method/MethodInterface.php, src/Model/RegisteredMethod.php, src/Service/SchemaGenerator.php, src/State/AvailableMethodDetails.php, src/State/AvailableMethodDetailsInterface.php, src/State/RegisteredMethodDetails.php, src/State/RegisteredMethodDetailsInterface.php, tests/php/Service/SchemaGeneratorTest.php, tests/php/State/AvailableMethodDetailsTest.php, tests/php/State/RegisteredMethodDetailsTest.php, tests/php/Stub/BasicMath/Method.php
Using some state encapsulation interfaces instead of arrays in schema generation process
=> API Move available and registered method details into encapsulated objects

src/Extension/SiteConfigExtension.php
By setting a minimum date on the DateField you get frontend and backend validation (on form save) that the selected date is greater than the specified minimum date on the field.
This is a problem when the field is hidden because it's optional, but still has a value in the past.
This was option one: remove the minimum date from the field. Option two would be to nullify the field when it's hidden from the form.
Fixes #50
=> FIX Grace period date no longer has a minimum requirement, since the field itself is optional

src/BackupCode/LoginHandler.php
Minor tweak to the "lead-in" text on logging in with back-up codes as discussed with @newleeland .
=> FIX Update wording on back-up codes

_config/store.yml, readme.md, src/Authenticator/LoginHandler.php, src/Store/SessionStore.php, src/Store/StoreInterface.php
create() and __construct() seem to be doing the same thing. This adjusts so that
__construct() is used instead, and the service is defined in config and handled
by Injector. Updated docs to reflect this change.
=> API StoreInterface is now injectable. Removed ::create() in favour of constructor.

_config/backupcodes.yml, src/BackupCode/Method.php, src/BackupCode/RegisterHandler.php, src/Service/BackupCodeGenerator.php, src/Service/BackupCodeGeneratorInterface.php, tests/php/BackupCode/RegisterHandlerTest.php, tests/php/Service/BackupCodeGeneratorTest.php, tests/php/Service/BackupCodeGeneratorTest/MockHashExtension.php
The default length is now 9 characters (alphanumeric, mixed case) and the default number generated is now 15 instead of 9.
Resolves https://github.com/silverstripe/silverstripe-mfa/issues/71
=> API Backup code generation has been moved into a BackupCodeGeneratorInterface service

src/Exception/HashFailedException.php, src/Service/BackupCodeGenerator.php, src/Service/BackupCodeGeneratorInterface.php, tests/php/Service/BackupCodeGeneratorTest.php
To ensure people don't do this in their projects. We discussed implementing something similar for hashing configuration to ensure a minimum amount of entropy, but decided that would be opinionated. If the hash and plaintext is the same it is not opinionated to say this is bad, however.
=> API BackupCodeGenerator::hash() now throws a HashFailedException when the result hash is the same as the plain text input

src/Authenticator/LoginHandler.php, src/Service/RegisteredMethodManager.php
Issue: #24
Also adds `$member->registerLoginFailure()` in order to track login attempts in auditor. This is not a complete implementation of #47, but is the start of it. The UI still needs to lock you out or redirect you away to somewhere else when you're locked out in the DB.
=> NEW Add extension points for audit logging in method registration, login and skip points

src/Authenticator/LoginHandler.php, src/Exception/InvalidMethodException.php, src/RequestHandler/LoginHandlerTrait.php, src/Service/EnforcementManager.php, src/Service/MethodRegistry.php, src/Store/SessionStore.php, src/Store/StoreInterface.php, tests/php/Authenticator/LoginHandlerTest.php, tests/php/Authenticator/RegisterHandlerTest.php
- Moves configuration for the required number of verified methods to the EnforcementManager
- `StoreInterface` now requires a member. A store cannot be created without one
- Parts of the code have been updated to handle the new `?StoreInterface` return type of `getStore`
- Updated API responses to return `403` instead of redirects when session timeouts occur
- Added a `LoginHandler` trait that provides methods for handling requests and responses to and from the MFA React app
- `SessionStore` implements `Serializable` so it can be added to the session directly
- Moved tracking of completed "verified methods" to `StoreInterface`.
- Moved loading of existing `StoreInterface`s to the interface
=> API Moving verification logic to a trait for easier re-usability

src/Authenticator/LoginHandler.php, src/BackupCode/LoginHandler.php, src/Method/Handler/LoginHandlerInterface.php, src/RequestHandler/LoginHandlerTrait.php, src/State/Result.php, src/Store/SessionStore.php, src/Store/StoreInterface.php, tests/php/Authenticator/LoginHandlerTest.php, tests/php/BackupCode/LoginHandlerTest.php, tests/php/BasicMath/MethodLoginHandlerTest.php, tests/php/State/ResultTest.php, tests/php/Store/SessionStoreTest.php, tests/php/Stub/BasicMath/MethodLoginHandler.php
* Return Result objects instead of booleans from verify() and subsequent methods, so we can communicate context to the frontend
* Add handling for when the member is locked out and pass it to the frontend
* Failures to handle JSON encoding of the state now throws an exception instead of a PHP type error (returning bool when should return string from serialize())
Resolves #47
=> API LoginHandler uses Result object instead of booleans, member is locked out via backend API after too many attempts

src/Authenticator/LoginHandler.php, src/BackupCode/RegisterHandler.php, src/Exception/RegistrationFailedException.php, src/Method/Handler/RegisterHandlerInterface.php, src/RequestHandler/BaseHandlerTrait.php, src/RequestHandler/LoginHandlerTrait.php, src/RequestHandler/RegistrationHandlerTrait.php, src/State/Result.php, tests/php/Authenticator/RegisterHandlerTest.php, tests/php/BackupCode/RegisterHandlerTest.php, tests/php/Stub/BasicMath/MethodRegisterHandler.php
- Created a new trait  that encapsulates logic for handling registration requests/responses to the MFA React App
- Created a  that has some methods for scaffolding the MFA React App not specific to either verification or registration
=> API Moving registration logic to a trait for easier re-usability

src/BackupCode/RegisterHandler.php, src/Service/BackupCodeGenerator.php, src/Service/BackupCodeGeneratorInterface.php, src/State/BackupCode.php, tests/php/Service/BackupCodeGeneratorTest.php
Fixes https://github.com/silverstripe/silverstripe-mfa/issues/111
This fixes an issue where PHP would coerce numeric strings to ints. They are always strings now.
=> API BackupCodeGenerator::generate() now returns an array of BackupCode instances

src/Authenticator/LoginHandler.php
This was causing a test failure on my local environment. Not sure why Travis would have different behaviour, but this is a valid safety improvement regardless.
=> Add safety to store access in finishRegistration

composer.json
We are testing our designs based on their output with the login-forms module installed. This will be the preferred approach to using the MFA module.
Resolves #95.
=> Add silverstripe/login-forms as direct dependency of silverstripe/mfa

src/BackupCode/VerifyHandler.php, src/Service/Notification.php, src/Service/RegisteredMethodManager.php, templates/Email/MFA/Notification_backupcodeused.ss, templates/Email/MFA/Notification_register.ss, templates/Email/MFA/Notification_removed.ss, tests/php/Authenticator/RegisterHandlerTest.yml, tests/php/BackupCode/VerifyHandlerTest.php, tests/php/Service/RegisteredMethodManagerTest.php
As a precaution users should be notified whenever their account details pertaining to security are updated, in order to let them respond to what could be a security breach. The easiest manner to do this is to send an email to their registered address.
Closes #67
=> NEW email notification for MFA settings update

src/Service/Notification.php, tests/php/Service/NotificationTest.php
This should've been part of the A/Cs (I don't remember if it was or not), but you should be able to turn off these notifications.
=> FIX MFA notifications can now be disabled via configuration

src/Service/EnforcementManager.php, tests/php/Service/EnforcementManagerTest.php, tests/php/Service/EnforcementManagerTest.yml
During recent work to have MFA always enabled (#186) an oversight was made in testing
meaning that a user could log in without verifying their registered MFA methods, if the site
was set to have MFA as optional.
=> FIX ability to log in without MFA verification

src/Authenticator/LoginHandler.php, src/Service/EnforcementManager.php, tests/php/Authenticator/LoginHandlerTest.php, tests/php/Service/EnforcementManagerTest.php
This fixes an issue that would continue to redirect the user to MFA after they logged in, ending up in a redirect loop. This patch checks whether it should redirect to MFA as well as checking if the registration is not complete yet before executing this logic.
Fixes https://github.com/silverstripe/silverstripe-mfa/issues/204
=> FIX Users without CMS access are now able to log in correctly

docs/en/backup-codes.md, src/Service/BackupCodeGenerator.php
This keeps the same amount (roughly) of entropy as 9 alphanumeric characters but is friendlier on the humans.
Resolves #230
=> NEW Update backup codes to use 12 lowercase letters

src/FormField/RegisteredMFAMethodListField.php, templates/SilverStripe/MFA/FormField/RegisteredMFAMethodListField.ss, tests/php/FormField/RegisteredMFAMethodListFieldTest.php, tests/php/FormField/RegisteredMFAMethodListFieldTest.yml
It was found that upon submission of a Member form in the CMS (e.g. to update a password)
there was a 500 server error being returned. The submission is of course attempting to
populate all the form fields with submitted data - the React form field for MFA management
is not a form field in the "accepts user input" sense, it is an interactive component
designed to perform actions directly - thus it has no value. No value means the PHP side
FormField instance is attempted to have `null` set as the value upon submission, which
disagrees strongly with the type hint of `Member`, and caused issues.
As this form field has two valid states - on where editing is possible and the member object
is always equal to `Security::getCurrentUser`, and a read only mode where the member may be any
valid …
=> FIX ensure RegisteredMFAFieldList always has a Member and never "not a Member"

src/Service/RegisteredMethodManager.php
Previously a method was added to test whether or not a method could be removed from a Member object. An extension hook exists to allow other actions to be checked when this method is called, however extensions could not alter the result of the canRemoveMethod check as was intended because the return value was not passed to the extension calls. Now it can be :)
=> FIX allow return value modification in extension hook for canRemoveMethod check

src/Authenticator/LoginHandler.php, tests/php/Authenticator/LoginHandlerTest.php, tests/php/Authenticator/LoginHandlerTest.yml
The usage of the BackURL key in the request does not work with MFA as it operates over many reqeusts, interrupting the 'normal' operation (default member authenticator logic).
MFA gets around this by storing the BackURL value in the session tied to the request - but this was being (correctly) cleared before the redirect is performed after a successful log in.
This commit fixes this by making a short lived store in memory for this value, and is still able to be utilised by the redirect logic from the 'normal' operation.
Resolves #250
=> FIX correctly redirect after successful log in

tests/php/Extension/AccountReset/SecurityExtensionTest.php
Was causing a test failure from global state in CWP. See https://github.com/silverstripe/cwp-recipe-kitchen-sink/issues/33.
=> FIX Ignore project defined password strength rules in MFA unit tests

lang/en.yml, templates/SilverStripe/MFA/Email/Notification_removed.ss, tests/Behat/Context/LoginContext.php, tests/php/Service/RegisteredMethodManagerTest.php
Upon registering a user is being sent an email to notify them that they have successfully added a multiple factor of authentication to their account on the site.
However due to a mix up with translation keys, the default text was being replaced with that for removing an authentication factor.
This commit fixes the translation key, and extends the tests to cover the body as well as the subject.
resolves #259
=> FIX Email correct content via translation key correction

src/Store/SessionStore.php, tests/php/Store/SessionStoreTest.php
Fixes #274 (but needs a backport). I think @indygriffiths confirmed this locally
=> FIX Defer member access for performance and cases where DB is not available on session start

readme.md, src/Service/MethodRegistry.php, tests/php/Service/MethodRegistryTest.php, tests/php/Stub/BasicMath/Method.php, tests/php/Stub/DuplicatedBasicMath/Method.php
* Docs update to clarify in readme
* MethodRegistry throws an exception if you register more than one method
Resolves #258
=> Prevent methods from being registered more than once

src/Extension/MemberExtension.php, src/FormField/RegisteredMFAMethodListField.php, tests/php/FormField/RegisteredMFAMethodListFieldTest.php
Using a DataObject as a field's value in SilverStripe 3 does not work, it ends up with infinite recursion while checking for whether the field it represents on the DataObject has been changed.
We don't need the Member object as the field value at all, so this removes some of the workaround code for previous issues with this and uses a member ID as the value instead.
Fixes https://github.com/silverstripe/silverstripe-mfa/issues/275
=> API RegisteredMFAMethodListField now expects a Member ID int as its value

src/Extension/ChangePasswordExtension.php, templates/SilverStripe/MFA/Authenticator/ChangePasswordHandler.ss
Both the schema endpoint and endpoint for the authentication method were wrong, resulting in the MFA screen hanging when a user clicks the link of the Password Reset email.
Fixes #297
=> Fix missing method on the Change Password handler endpoints

package.json
`bootstrap` was already a dependency but it wasn't explicitly stated. In the end `reactstrap-confirm` was already providing it for us.
=> Add missing bootstrap dependency

composer.json, src/Report/EnabledMembers.php, tests/php/Report/EnabledMembersTest.php, tests/php/Report/EnabledMembersTest.yml, tests/php/Stub/Null/Method.php
In order to aid administrators with the up-take of MFA on their site, a
report can be used to show which users are yet to set up a method, etc.
Resolves #114
=> NEW report to show members who have registered an MFA method

src/Authenticator/LoginHandler.php, src/BackupCode/RegisterHandler.php
Issue: https://github.com/silverstripe/silverstripe-mfa/issues/239. Requires https://github.com/silverstripe/silverstripe-userhelp-   content/pull/137.
=> NEW Add links to userhelp documentation

composer.json
In `silverstripe/subsites 2.3.1`, we introduced a fix that was causing the MFA module to stop authenticating users when used alongside Subsites. That fix is mandatory for a stable install - so this PR marks earlier versions as conflicting.
=> FIX Prevent incompatible versions of Subsites from installing alongside MFA

docs/en/userguide/01_User_manual/03_Using_security_keys.md
Security keys are not recommended for use with Subsites. This makes a note in the userhelp docs.
Resolves https://github.com/silverstripe/silverstripe-webauthn-authenticator/issues/58
[ci skip]
=> DOCS userhelp note for subsites

composer.json
MFA tries to load language JS files that haven't been exposed.
This PR expose the `client/lang` folder as was intendended.
=> BUG Expose the client/lang directory so we can load JS side translation properly
