silverstripe/silverstripe-mfa

src/Authenticator/LoginHandler.php
This PR adjusts the API endpoints for the MFA LoginHandler to support registration (in the future) and retrieving the schema for the current state of the Member.
=> Flesh out URL handlers for MFA endpoints

tests/php/BasicMath/MethodLoginHandlerTest.php, tests/php/BasicMath/MethodTest.php, tests/php/Stub/BasicMath/Method.php, tests/php/Stub/BasicMath/MethodLoginHandler.php, tests/php/Stub/BasicMath/MethodRegisterHandler.php
This method isn't a real method and really shouldn't exist as anything other than reference material (or as a handy testing stub!)
=> Moving BasicMath method to test folder as a stub method

src/Authenticator/LoginHandler.php
Missed from the previous backup codes PR
=> FIX Pass method interface instead of URL segment in startLogin()

src/Authenticator/LoginHandler.php, tests/php/Authenticator/LoginHandlerTest.php, tests/php/BasicMath/MethodLoginHandlerTest.php
BasicMath now has JS components & has corrected verify logic.
Also updated some code that was too reliant on variables being defined
=> FIX Fixing phpunit test failures

src/Authenticator/LoginHandler.php, src/Service/EnforcementManager.php, tests/php/Authenticator/LoginHandlerTest.php, tests/php/Service/EnforcementManagerTest.php
Fixes https://github.com/silverstripe/silverstripe-mfa/issues/88
=> FIX No longer redirect to MFA when MFA is not enabled

_config/logging.yml, readme.md, src/Authenticator/LoginHandler.php, src/Dev/State/LoggerTestState.php
=> NEW MFA module now has a logger and test state to clear user defined handlers in unit testing

composer.json, src/Authenticator/LoginHandler.php, src/Controller/AdminRegistrationController.php, src/RequestHandler/BaseHandlerTrait.php, tests/php/Authenticator/LoginHandlerTest.php, tests/php/Authenticator/RegisterHandlerTest.php, tests/php/Controller/AdminRegistrationControllerTest.php
Requires https://github.com/silverstripe/silverstripe-security-extensions/pull/1
=> NEW Enforce sudo mode on posted MFA actions

src/Controller/AdminRegistrationController.php, tests/php/Controller/AdminRegistrationControllerTest.php
=> FIX Allow any logged in user to access the AdminRegistrationController, it implements its own checks

_config/admin.yml
Fixes https://github.com/silverstripe/silverstripe-mfa/issues/175
=> FIX Apply MFA requirements to all LeftAndMain controllers to avoid missing Requirements from PJAX requests

src/Service/EnforcementManager.php, tests/php/Authenticator/LoginHandlerTest.yml, tests/php/Service/EnforcementManagerTest.php, tests/php/Service/EnforcementManagerTest.yml
=> NEW Only redirect to MFA when the current member has access to part of the admin area

docs/en/datastores.md, docs/en/debugging.md, docs/en/encryption.md, docs/en/local-development.md, readme.md, src/Service/EnforcementManager.php, tests/php/Service/EnforcementManagerTest.php
=> NEW Add ability to disable MFA via YAML configuration, restructure documentation and add example to "local-development.md"

src/Service/EnforcementManager.php, tests/php/Service/EnforcementManagerTest.php
Fixes https://github.com/silverstripe/silverstripe-mfa/issues/206
=> FIX No longer redirects to MFA when no methods are installed on the system

src/RequestHandler/RegistrationHandlerTrait.php
=> FIX Subsequent admin requests to manage MFA methods no longer reset the CSRF token

.travis.yml
Tests will now run! (They still fail, but one challenge at a time.)
=> Adjust Travis config to support SS3

docs/en/datastores.md, src/Authenticator/LoginHandler.php
=> FIX SessionStore no longer persists the member's password during MFA login

src/Extension/SiteConfigExtension.php
This is OOB with SS4 but is opt-in in SS3
=> FIX Show jQuery datepicker on MFA grace period selection field

_config/config.yml, docs/en/other-authenticators.md, readme.md
Part of https://github.com/silverstripe/silverstripe-mfa/issues/173
=> DOCS Add hypothetical guide to integrating MFA into another authenticator e.g. LDAP

docs/en/encryption.md, docs/en/security.md, readme.md
=> DOCS Add security documentation incl. login attempts, fix readme links to "create method" files

src/BackupCode/RegisterHandler.php, tests/php/BackupCode/RegisterHandlerTest.php
Fixes https://github.com/silverstripe/silverstripe-mfa/issues/263
=> FIX Prevent early backup code generation during registration process

src/Authenticator/LoginHandler.php
This also simplifies some of the logic in the initial method of our `LoginHandler`. It makes sense to put all the delegation logic in one place.
=> FIX Regenerate session ID on registration to prevent session fixation

src/Report/EnabledMembers.php, tests/php/Report/EnabledMembersFunctionalTest.php, tests/php/Report/EnabledMembersTest.php, tests/php/Report/EnabledMembersTest.yml
=> API Enabled members report is now performant, no count column/filter, extra method filter options

src/Extension/MemberExtension.php, src/FormField/RegisteredMFAMethodListField.php, tests/php/FormField/RegisteredMFAMethodListFieldTest.php
Port of #291 for SS4. See justification on that PR.
This is an API change at RC stage.
=> API RegisteredMFAMethodListField now expects a Member ID int as its value

src/Extension/AccountReset/SecurityAdminExtension.php, tests/php/Report/EnabledMembersFunctionalTest.php
=> FIX setLogger now exists on SecurityAdminExtension

src/FormField/RegisteredMFAMethodListField.php
=> FIX XHR requests can now resolve the current Member correctly

src/Extension/SiteConfigExtension.php
=> FIX MFA help link now points directly to MFA documentation on the userhelp site

src/Service/SchemaGenerator.php
See https://github.com/silverstripe/silverstripe-mfa/issues/340
=> FIX Images now resolve correctly when project is installed in a subfolder
